Allow preserving original target host or port
When the host or port specified is "original" then it's not changed. The
test suite was extended to cover four different possible use cases.

diff --git a/test b/test
--- a/test
+++ b/test
@@ -4,31 +4,55 @@ set -eu
 
 export LD_LIBRARY_PATH="."
 
-DATA="foobar"
-TEMP_FILE=`mktemp`
+function test_netredirect {
+    SERVER_ADDR=$1
+    SERVER_PORT=$2
+    REDIRECT_ADDR=$3
+    REDIRECT_PORT=$4
 
-# Start a test server that will receive our data.
-nc -l -p 8888 >& $TEMP_FILE &
-NC_PID=$!
+    if [ "${REDIRECT_ADDR}" = "original" ]; then
+        REDIRECT_ADDR=${SERVER_ADDR}
+    fi
 
-# Kill the server and remove the data file when exiting.
-function cleanup {
-    set +e
-    kill $NC_PID >& /dev/null
-    rm $TEMP_FILE
-    set -e
+    if [ "${REDIRECT_PORT}" = "original" ]; then
+        REDIRECT_PORT=${SERVER_PORT}
+    fi
+
+    DATA="foobar"
+    TEMP_FILE=`mktemp`
+
+    # Start a test server that will receive our data.
+    nc -l -p ${REDIRECT_PORT} >& $TEMP_FILE &
+    NC_PID=$!
+
+    # Kill the server and remove the data file when exiting.
+    function cleanup {
+        set +e
+        kill $NC_PID >& /dev/null
+        rm $TEMP_FILE
+        set -e
+    }
+    trap cleanup EXIT
+
+    # Wait a second for the server to set up.
+    sleep 1
+
+    # Send data to the server.
+    echo -n "$DATA" | ./netredirect ${REDIRECT_ADDR} ${REDIRECT_PORT} \
+        nc -q 0 -w 5 ${SERVER_ADDR} ${SERVER_PORT}
+
+    # Verify the data.
+    RECEIVED=`cat $TEMP_FILE`
+    if [ "$DATA" != "$RECEIVED" ]; then
+        echo "Error: sent \"$DATA\" but received \"$RECEIVED\"" 2>1
+        exit 1
+    fi
+
+    echo -n .
 }
-trap cleanup EXIT
 
-# Wait a second for the server to set up.
-sleep 1
-
-# Send data to the server.
-echo -n "$DATA" | ./netredirect 127.0.0.1 8888 nc -q 0 -w 5 1.2.3.4 7777
-
-# Verify the data.
-RECEIVED=`cat $TEMP_FILE`
-if [ "$DATA" != "$RECEIVED" ]; then
-    echo "Error: sent \"$DATA\" but received \"$RECEIVED\"" 2>1
-    exit 1
-fi
+test_netredirect 10.0.0.1 8000 127.0.0.1 8001
+test_netredirect 10.0.0.1 8000 127.0.0.1 original
+test_netredirect 127.0.0.1 8000 original original
+test_netredirect 127.0.0.1 8000 original 8001
+echo
